config/routes.rb
Rails.application.routes.draw do

	resources :beacons
	resources :majors
	resources :accounts
	resources :users
	
	# devise_for :users
	devise_for :user, :controllers => { :confirmations => "confirmations" }
	devise_scope :user do
		put 'user/confirmation', to: 'confirmations#update'
	end
	
	get 'static_pages/home'
	get 'static_pages/about'
	get 'static_pages/contact'
	get 'static_pages/imprint'
	get 'static_pages/privacy'


	devise_scope :user do
		get "sign_in", :to => "devise/sessions#new"
		get "sign_out", :to => "devise/sessions#destroy"
	end

	mount API::Base, at: "/"
	mount GrapeSwaggerRails::Engine, at: "/documentation"



	root to: 'static_pages#home'
end

app/models/beacon.rb
class Beacon < ApplicationRecord

	belongs_to :account
	belongs_to :major

	validates :name, presence: true
	validates :enter_text, presence: true
	validates :exit_text, presence: true

	extend FriendlyId
  	friendly_id :name, use: :slugged

	before_create :set_minor_id

  	def set_minor_id
      self.minor_id = ApplicationController.helpers.generate_minor_id(self.major_id)
    end
end

app/controllers/api/v1/beacons.rb
# module API
#   module V1
#     class Beacons < Grape::API
#       include API::V1::Defaults

#       resource :beacons do
#         desc "Return all beacons"
#         get "", root: :beacons do
#           Beacon.all
#         end

#         desc "Return a beacon"
#         params do
#           requires :id, type: String, desc: "ID of the beacon"
#         end
#         get ":id", root: "beacon" do
#           Beacon.where(id: permitted_params[:id]).first!
#         end
#       end
#     end
#   end
# end



module API
  module V1
    class Beacons < Grape::API
      include API::V1::Defaults

      resource :beacons do
        desc "Return all beacons"
        get "", root: :beacons do
          Beacon.all
        end

        desc "Return a beacon"
        params do
          # requires :major_id, type: String, desc: "MajorID of the beacon"
          # requires :minor_id, type: , desc: "MinorID of the beacon"
          requires :major_id, :minor_id, type: String, desc: 'combined (unique) major/minor beacon id'
        end


        get ":major_id/:minor_id", root: "beacon" do
          Beacon.where(major_id: permitted_params[:major_id]).where(minor_id: permitted_params[:minor_id]).first!
        end

      end
    end
  end
end

app/controllers/beacons_controller.rb
class BeaconsController < ApplicationController
  before_action :set_beacon, only: [:show, :edit, :update, :destroy]

  # GET /beacons
  # GET /beacons.json
  def index
    @beacons = Beacon.all
  end

  # GET /beacons/1
  # GET /beacons/1.json
  def show
  end

  # GET /beacons/new
  def new
    @beacon = Beacon.new
  end

  # GET /beacons/1/edit
  def edit
  end

  # POST /beacons
  # POST /beacons.json
  def create
    
    @beacon = Beacon.new(beacon_params)

    # @major = Major.create
    # @minor = Minor.create
    # @beacon.major_id = @major.id
    # @beacon.minor_id = @minor.id

    respond_to do |format|
      if @beacon.save

        # @major = Major.create
        # @minor = Minor.create
        # # @beacon.major_id = @major.id
        # # @beacon.minor_id = @minor.id
        # @beacon.update({"major_id"=>@major.id, "minor_id"=>@minor.id})

        flash[:notice] = 'Beacon was successfully created.'
        format.html { redirect_to action: "index" }
      else
        flash[:alert] = custom_error_message_rendering(@beacon.errors)
        format.html { redirect_to action: "new" }
      end
    end

  end

  # PATCH/PUT /beacons/1
  # PATCH/PUT /beacons/1.json
  def update
    respond_to do |format|
      if @beacon.update(beacon_params)
        flash[:notice] = 'Beacon was successfully updated.'
        format.html { redirect_to action: "index" }
      else
        flash[:alert] = custom_error_message_rendering(@beacon.errors)
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /beacons/1
  # DELETE /beacons/1.json
  def destroy
    @beacon.destroy
    respond_to do |format|
      format.html { redirect_to beacons_url, notice: 'Beacon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beacon
      # @beacon = Beacon.find(params[:id])
      @beacon = Beacon.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beacon_params
      # params.require(:beacon).permit(:major_name, :major_description, :minor_name, :minor_description, :enter_text, :exit_text, :major_id, :minor_id)
      params.require(:beacon).permit(:name, :slug, :description, :enter_text, :exit_text, :major_id, :minor_id, :account_id)
    end
end

app/helpers/beacons_helper.rb
module BeaconsHelper
end

app/views/beacons/_form.html.erb
<%= form_for beacon, local: true do |form| %>
  <div class="card mb-3">
    <div class="card-body">


        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Account</label>
          <div class="col-sm-10">
            <%= form.collection_select(:account_id, Account.all, :id, :name, { :include_blank => "Please Select" }, { :class => "select2-multiple select2-single form-control" }) %>
          </div>
        </div>


         <div class="form-group row">
          <label class="col-sm-2 col-form-label">Major</label>
          <div class="col-sm-10">
            <%= form.collection_select(:major_id, Major.all, :id, :name, { :include_blank => "Please Select" }, { :class => "select2-multiple select2-single form-control" }) %>
          </div>
        </div>



         <div class="form-group row">
          <label class="col-sm-2 col-form-label">Name</label>
          <div class="col-sm-10">
            <%= form.text_field :name, class: "form-control" %>
          </div>
        </div>
        
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Description</label>
          <div class="col-sm-10">
            <%= form.text_area :description, :rows => 5, class: "form-control" %>
          </div>
        </div>
        
         <!-- <div class="form-group row">
          <label class="col-sm-2 col-form-label">Major description</label>
          <div class="col-sm-10">
            <%#= form.text_area :major_description, :rows => 5, class: "form-control" %>
          </div>
        </div> -->


        <!-- <div class="form-group row">
          <label class="col-sm-2 col-form-label">Minor name</label>
          <div class="col-sm-10">
            <%#= form.text_field :minor_name, class: "form-control" %>
          </div>
        </div>
        
         <div class="form-group row">
          <label class="col-sm-2 col-form-label">Minor description</label>
          <div class="col-sm-10">
            <%#= form.text_area :minor_description, :rows => 5, class: "form-control" %>
          </div>
        </div> -->

        </div>
    </div>

    <!--
    <div class="card mb-3">
      <div class="card-body">
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Major</label>
          <div class="col-sm-10">
            <%#= form.collection_select(:major_id, Major.all, :id, :name, { :include_blank => "Please Select" }, { :class => "select2-multiple select2-single form-control" }) %>
          </div>
        </div>

          <div class="form-group row">
          <label class="col-sm-2 col-form-label">Minor</label>
          <div class="col-sm-10">
            <%#= form.collection_select(:minor_id, Minor.all, :id, :name, { :include_blank => "Please Select" }, { :class => "select2-multiple select2-single form-control" }) %>
          </div>
        </div>
      </div>
    </div>
    -->

    <div class="card mb-3">
    <div class="card-body">

        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Enter Text</label>
          <div class="col-sm-10">
            <%= form.text_area :enter_text, :rows => 5, class: "form-control" %>
          </div>
        </div>

         <div class="form-group row">
          <label class="col-sm-2 col-form-label">Exit Text</label>
          <div class="col-sm-10">
            <%= form.text_area :exit_text, :rows => 5, class: "form-control" %>
          </div>
        </div>
      </div>
    </div>

    <div class="text-right">
      <%= form.submit class: "btn btn-outline-secondary" %>
    </div>
<% end %>

app/views/beacons/edit.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 margin-bottom-20">
  <h1 class="h2">Editing Beacon <small class="text-muted">(<%= @beacon.name %>)</small></h1>
</div>
<%= render 'form', beacon: @beacon %>

app/views/beacons/index.html.erb
<div class="row mb-3">
  <div class="col-6"><h3>Beacons</h3></div>
  <div class="col-6 text-right">
    <%= link_to 'New Beacon', new_beacon_path, class: "btn btn-outline-secondary" %>
    <%#= link_to ('<i class="fas fa-code"></i> JSON <small>(all)</small>').html_safe, "/beacons.json", :target=>"_blank", class: "btn btn-outline-info ml-3" %>
  </div>
</div>

<table class="table table-hover">
  <tbody>
      <% @beacons.each do |beacon| %>
      <tr>
        <td class="align-middle"><%= beacon.name %></td>
        <td class="align-middle"><em class="text-muted"><%= beacon.description.truncate(50) if beacon.description %></em></td>
        <td class="align-middle"><span class="badge badge-warning"><%= beacon.account.name if beacon.account %></span></td>
        <td class="align-middle"><span class="badge badge-info"><%= beacon.major.name if beacon.major %></span></td>
        <td class="align-middle"><span class="badge badge-success"><%= beacon.major.major_id.to_s + "," + beacon.minor_id.to_s %></span></td>
        <td class="text-right align-middle">
          <%= link_to 'Edit', edit_beacon_path(beacon), class: "btn btn-sm btn-outline-secondary" %>
          <%= link_to 'Destroy', beacon, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-secondary" %>
          <%#= link_to ('<i class="fas fa-code"></i> JSON ').html_safe, "/beacons/#{beacon.slug}.json", :target=>"_blank", class: "btn btn-sm btn-outline-info ml-3" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/beacons/new.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 margin-bottom-20">
  <h1 class="h2">New Beacon</h1>
</div>
<%= render 'form', beacon: @beacon %>

app/views/beacons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Major name:</strong>
  <%= @beacon.major_name %>
</p>

<p>
  <strong>Major description:</strong>
  <%= @beacon.major_description %>
</p>

<p>
  <strong>Minor name:</strong>
  <%= @beacon.minor_name %>
</p>

<p>
  <strong>Minor description:</strong>
  <%= @beacon.minor_description %>
</p>

<p>
  <strong>Enter text:</strong>
  <%= @beacon.enter_text %>
</p>

<p>
  <strong>Exit text:</strong>
  <%= @beacon.exit_text %>
</p>

<%= link_to 'Edit', edit_beacon_path(@beacon) %> |
<%= link_to 'Back', beacons_path %>