config/routes.rb
Rails.application.routes.draw do

	resources :beacons
	resources :majors
	resources :accounts
	resources :users
	
	# devise_for :users
	devise_for :user, :controllers => { :confirmations => "confirmations" }
	devise_scope :user do
		put 'user/confirmation', to: 'confirmations#update'
	end
	
	get 'static_pages/home'
	get 'static_pages/about'
	get 'static_pages/contact'
	get 'static_pages/imprint'
	get 'static_pages/privacy'


	devise_scope :user do
		get "sign_in", :to => "devise/sessions#new"
		get "sign_out", :to => "devise/sessions#destroy"
	end

	mount API::Base, at: "/"
	mount GrapeSwaggerRails::Engine, at: "/documentation"



	root to: 'static_pages#home'
end

app/models/major.rb
class Major < ApplicationRecord

	has_many :beacons

	validates :name, presence: true
	
	extend FriendlyId
  	friendly_id :name, use: :slugged

  	before_create :set_major_id

  	def set_major_id
      self.major_id = ApplicationController.helpers.generate_major_id
    end
end

app/controllers/majors_controller.rb
class MajorsController < ApplicationController
  before_action :set_major, only: [:show, :edit, :update, :destroy]

  # GET /majors
  # GET /majors.json
  def index
    @majors = Major.all
  end

  # GET /majors/1
  # GET /majors/1.json
  def show
  end

  # GET /majors/new
  def new
    @major = Major.new
  end

  # GET /majors/1/edit
  def edit
  end

  # POST /majors
  # POST /majors.json
  def create
    @major = Major.new(major_params)

    respond_to do |format|
      if @major.save
        flash[:notice] = 'Major was successfully created.'
        format.html { redirect_to action: "index" }
      else
        flash[:alert] = custom_error_message_rendering(@major.errors)
        format.html { redirect_to action: "new" }
      end
    end
  end

  # PATCH/PUT /majors/1
  # PATCH/PUT /majors/1.json
  def update
    respond_to do |format|
      if @major.update(major_params)
        flash[:notice] = 'Major was successfully updated.'
        format.html { redirect_to action: "index" }
      else
        flash[:alert] = custom_error_message_rendering(@major.errors)
        format.html { render action: 'edit' }
      end
    end
  end


  # DELETE /majors/1
  # DELETE /majors/1.json
  def destroy
    @major.destroy
    respond_to do |format|
      format.html { redirect_to majors_url, notice: 'Major was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_major
      # @major = Major.find(params[:id])
      @major = Major.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def major_params
      params.require(:major).permit(:name, :description, :slug, :major_id, :account_id)
    end
    
end

app/helpers/majors_helper.rb
module MajorsHelper
end

app/views/majors/_form.html.erb
<%= form_for major, local: true do |form| %>
  <div class="card mb-3">
    <div class="card-body">

       <!--  <div class="form-group row">
          <label class="col-sm-2 col-form-label">Account</label>
          <div class="col-sm-10">
            <%#= form.collection_select(:account_id, Account.all, :id, :name, { :include_blank => "Please Select" }, { :class => "select2-multiple select2-single form-control" }) %>
          </div>
        </div> -->

         <div class="form-group row">
          <label class="col-sm-2 col-form-label">Name</label>
          <div class="col-sm-10">
            <%= form.text_field :name, class: "form-control" %>
          </div>
        </div>
        
         <div class="form-group row">
          <label class="col-sm-2 col-form-label">Description</label>
          <div class="col-sm-10">
            <%= form.text_area :description, :rows => 5, class: "form-control" %>
          </div>
        </div>
      </div>
    </div>

    <div class="text-right">
      <%= form.submit class: "btn btn-outline-secondary" %>
    </div>
<% end %>

app/views/majors/edit.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 margin-bottom-20">
  <h1 class="h2">Editing Major <small class="text-muted">(<%= @major.name %>)</small></h1>
</div>
<%= render 'form', major: @major %>

app/views/majors/index.html.erb
<div class="row mb-3">
  <div class="col-6"><h3>Majors</h3></div>
  <div class="col-6 text-right">
    <%= link_to 'New Major', new_major_path, class: "btn btn-outline-secondary" %>
    <%#= link_to ('<i class="fas fa-code"></i> JSON <small>(all)</small>').html_safe, "/majors.json", :target=>"_blank", class: "btn btn-outline-info ml-3" %>
  </div>
</div>

<table class="table table-hover">
  <tbody>
    <% @majors.each do |major| %>
      <tr>
        <td class="align-middle"><%= major.name %></td>
        <td class="align-middle"><em class="text-muted"><%= major.description.truncate(50) if major.description %></em></td>
        <!-- <td class="align-middle"><span class="badge badge-warning"><%#= major.account.name if major.account %></span></td> -->
        <!-- <td class="align-middle"><span class="badge badge-secondary"><%#= (major.minors.count.to_s + " minors") if major.minors %></span></td> -->
        <td class="text-right align-middle">
          <%= link_to 'Edit', edit_major_path(major), class: "btn btn-sm btn-outline-secondary" %>
          <%= link_to 'Destroy', major, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-secondary" %>
          <%#= link_to ('<i class="fas fa-code"></i> JSON ').html_safe, "/majors/#{major.slug}.json", :target=>"_blank", class: "btn btn-sm btn-outline-info ml-3" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/majors/new.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 margin-bottom-20">
  <h1 class="h2">New Major</h1>
</div>
<%= render 'form', major: @major %>

app/views/majors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @major.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @major.description %>
</p>

<p>
  <strong>Account:</strong>
  <%= @major.account_id %>
</p>

<%= link_to 'Edit', edit_major_path(@major) %> |
<%= link_to 'Back', majors_path %>