config/routes.rb
Rails.application.routes.draw do

	resources :beacons
	resources :majors
	resources :accounts
	resources :users
	
	# devise_for :users
	devise_for :user, :controllers => { :confirmations => "confirmations" }
	devise_scope :user do
		put 'user/confirmation', to: 'confirmations#update'
	end
	
	get 'static_pages/home'
	get 'static_pages/about'
	get 'static_pages/contact'
	get 'static_pages/imprint'
	get 'static_pages/privacy'


	devise_scope :user do
		get "sign_in", :to => "devise/sessions#new"
		get "sign_out", :to => "devise/sessions#destroy"
	end

	mount API::Base, at: "/"
	mount GrapeSwaggerRails::Engine, at: "/documentation"



	root to: 'static_pages#home'
end

app/views/layouts/partials/_admin_bar.html.erb
<% if user_signed_in? %>
	<div class="admin-bar p-1 px-md-4 border-bottom">
		<div class="row">
			<div class="col-md-12 text-right">

				<small>Signed is as: <strong><%= current_user.email %></strong></small>
				
				<a class="btn btn-admin btn-sm ml-2" class="dropdown-toggle" href="#" role="button" id="admin_menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<i class='fas fa-cog'></i>
				</a>

				<div class="dropdown-menu" aria-labelledby="admin_menu">
					<%= link_to "Users", users_path, class: "dropdown-item" %>
					<%= link_to "Accounts", accounts_path, class: "dropdown-item" %>
					
					<%= link_to "Majors", majors_path, class: "dropdown-item" %>
					<%= link_to "Beacons", beacons_path, class: "dropdown-item" %>
					<%#= link_to "Minors", minors_path, class: "dropdown-item" %>
				</div>

			</div>
		</div>
	</div>
<% end %>

app/views/layouts/partials/_flash_alerts.html.erb
<% if notice && notice != "" %>
	<div class="alert alert-success alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<%= notice.html_safe %>
	</div>
<% end %>

<% if alert && alert != "" %>
	<div class="alert alert-danger alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<%= alert.html_safe %>
	</div>
<% end %>

app/views/layouts/partials/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <!-- <div class="row">
    <div class="col-12 col-md">
      <img class="mb-2" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
      <small class="d-block mb-3 text-muted">&copy; 2019</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Attendee Management</a></li>
        <li><a class="text-muted" href="#">Promotion and Navigation</a></li>
        <li><a class="text-muted" href="#">Networking</a></li>
        <li><a class="text-muted" href="#">Note taking</a></li>
        <li><a class="text-muted" href="#">Schedule</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Resource</a></li>
        <li><a class="text-muted" href="#">Resource name</a></li>
        <li><a class="text-muted" href="#">Another resource</a></li>
        <li><a class="text-muted" href="#">Final resource</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Team</a></li>
        <li><a class="text-muted" href="#">Locations</a></li>
        <li><a class="text-muted" href="#">Privacy</a></li>
        <li><a class="text-muted" href="#">Terms</a></li>
      </ul>
    </div>
  </div> -->
</footer>

app/views/layouts/partials/_nav.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom">
	<!-- <h5 class="my-0 mr-md-auto font-weight-normal">Notify</h5> -->

		<%= image_tag "logo_small.png", class: "header-logo my-0 mr-md-auto" %>

		<nav class="my-2 my-md-0 mr-md-3">
			<!-- <a class="p-2 text-dark" href="#">Features</a> -->
			<!-- <a class="p-2 text-dark" href="#">About</a> -->
			<!-- <a class="p-2 text-dark" href="#">Support</a> -->
			<!-- <a class="p-2 text-dark" href="#">Contact</a> -->
		</nav>

		<% if user_signed_in? %>
			<%= link_to "Sign out", sign_out_path, class: "btn btn-sign_in" %>
		<% else %>
			<%= link_to "Sign in", sign_in_path, class: "btn btn-sign_in" %>
		<% end %>

</div>